import type { ApplicantDetail } from '@/interfaces/_applicantDetailInterface.js'

export const dummyApplicantArray: ApplicantDetail[] = [
  {
    id: 12,
    uuid: '550e8400-e29b-41d4-a716-446655440012',
    applicant: {
      nickname: 'dev_juwon',
      gender: 'MALE',
      profile_img_url: 'https://cdn.example.com/profiles/juwon.png',
    },
    available_time: '평일 저녁, 주말 오전',
    has_study_experience: true,
    status: 'PENDING',
    applied_at: '2025-10-16 11:25',
    self_introduction: '안녕하세요, 프론트엔드 개발자 주원입니다.',
    motivation: '같이 성장하는 스터디 문화를 만들어보고 싶어요.',
    objective: 'React 심화 학습과 협업 경험 향상.',
    study_experience: '부트캠프 프로젝트 경험 있음',
  },
  {
    id: 13,
    uuid: '550e8400-e29b-41d4-a716-446655440013',
    applicant: {
      nickname: 'frontend_park',
      gender: 'FEMALE',
      profile_img_url: 'https://cdn.example.com/profiles/juwon.png',
    },
    available_time: '주중 오후',
    has_study_experience: false,
    status: 'ACCEPTED',
    applied_at: '2025-10-15 19:48',
    self_introduction: 'UI 구현에 관심이 많은 신입 개발자입니다.',
    motivation: '팀 프로젝트 경험을 쌓고 싶습니다.',
    objective: '실무 중심의 웹 개발 역량 강화.',
    study_experience: '없음',
  },
  {
    id: 14,
    uuid: '550e8400-e29b-41d4-a716-446655440014',
    applicant: {
      nickname: 'js_kim',
      gender: 'MALE',
      profile_img_url: 'https://cdn.example.com/profiles/js_kim.jpg',
    },
    available_time: '주말 전일',
    has_study_experience: true,
    status: 'REJECTED',
    applied_at: '2025-10-14 10:32',
    self_introduction: 'JavaScript를 좋아하는 백엔드 지망생입니다.',
    motivation: 'JS 심화 개념을 정리하고 싶습니다.',
    objective: 'Node.js 기반 서버 개발 학습.',
    study_experience: '사이드 프로젝트 진행 경험 있음',
  },
  {
    id: 15,
    uuid: '550e8400-e29b-41d4-a716-446655440015',
    applicant: {
      nickname: 'react_sujin',
      gender: 'FEMALE',
      profile_img_url: 'https://cdn.example.com/profiles/sujin.png',
    },
    available_time: '평일 오후 7시 이후',
    has_study_experience: true,
    status: 'PENDING',
    applied_at: '2025-10-18 21:05',
    self_introduction: 'React에 진심인 프론트엔드 개발자입니다.',
    motivation: '실제 프로젝트 구조를 배우고 싶습니다.',
    objective: 'Next.js 활용 능력 향상.',
    study_experience: '부트캠프 수료 후 스터디 진행 중',
  },
  {
    id: 16,
    uuid: '550e8400-e29b-41d4-a716-446655440016',
    applicant: {
      nickname: 'backend_lee',
      gender: 'MALE',
      profile_img_url: 'https://cdn.example.com/profiles/juwon.png',
    },
    available_time: '주말 오후',
    has_study_experience: false,
    status: 'ACCEPTED',
    applied_at: '2025-10-12 14:44',
    self_introduction: 'Node.js로 서버 구축에 관심 있습니다.',
    motivation: 'API 설계에 대한 실무 감각을 익히고 싶습니다.',
    objective: 'Express와 DB 연동 이해.',
    study_experience: '없음',
  },
  {
    id: 17,
    uuid: '550e8400-e29b-41d4-a716-446655440017',
    applicant: {
      nickname: 'uiux_haeun',
      gender: 'FEMALE',
      profile_img_url: 'https://cdn.example.com/profiles/haeun.jpg',
    },
    available_time: '평일 오전',
    has_study_experience: true,
    status: 'PENDING',
    applied_at: '2025-10-20 09:18',
    self_introduction: '디자인과 개발의 경계를 넘나드는 사람입니다.',
    motivation: '사용자 중심 UI를 개발해보고 싶어요.',
    objective: 'UX 개선 중심 프론트엔드 학습.',
    study_experience: 'UI/UX 기반 팀 프로젝트 참여',
  },
  {
    id: 18,
    uuid: '550e8400-e29b-41d4-a716-446655440018',
    applicant: {
      nickname: 'node_min',
      gender: 'MALE',
      profile_img_url: 'https://cdn.example.com/profiles/min.png',
    },
    available_time: '주중 저녁, 주말 오후',
    has_study_experience: false,
    status: 'REJECTED',
    applied_at: '2025-10-11 17:55',
    self_introduction: '서버 사이드 렌더링에 관심이 많습니다.',
    motivation: '백엔드-프론트 협업 이해도를 높이고 싶어요.',
    objective: 'Node.js + React 통합 학습.',
    study_experience: '없음',
  },
  {
    id: 19,
    uuid: '550e8400-e29b-41d4-a716-446655440019',
    applicant: {
      nickname: 'design_jina',
      gender: 'FEMALE',
      profile_img_url: 'https://cdn.example.com/profiles/jina.png',
    },
    available_time: '평일 오후, 주말 오전',
    has_study_experience: true,
    status: 'ACCEPTED',
    applied_at: '2025-10-19 15:37',
    self_introduction: '디자인 감각을 살린 프론트엔드 개발자입니다.',
    motivation: '팀 프로젝트 협업 능력을 키우고 싶습니다.',
    objective: '디자인 시스템 구현 학습.',
    study_experience: '프로젝트 UI 컴포넌트 제작 경험 있음',
  },
  {
    id: 20,
    uuid: '550e8400-e29b-41d4-a716-446655440020',
    applicant: {
      nickname: 'vue_jihye',
      gender: 'FEMALE',
      profile_img_url: 'https://cdn.example.com/profiles/jihye.png',
    },
    available_time: '평일 저녁',
    has_study_experience: true,
    status: 'PENDING',
    applied_at: '2025-10-17 18:40',
    self_introduction: 'Vue와 React 모두 다뤄본 개발자입니다.',
    motivation: '비슷한 관심사의 사람들과 함께 공부하고 싶어요.',
    objective: '컴포넌트 기반 아키텍처 심화.',
    study_experience: '사이드 프로젝트 경험 있음',
  },
  {
    id: 21,
    uuid: '550e8400-e29b-41d4-a716-446655440021',
    applicant: {
      nickname: 'ai_junho',
      gender: 'MALE',
      profile_img_url: 'https://cdn.example.com/profiles/junho.png',
    },
    available_time: '주말 오전',
    has_study_experience: false,
    status: 'PENDING',
    applied_at: '2025-10-22 09:02',
    self_introduction: 'AI 기술과 웹의 융합에 관심이 있습니다.',
    motivation: '웹 서비스에 AI 기능을 접목해보고 싶어요.',
    objective: 'AI API 활용 및 모델 연동 학습.',
    study_experience: '없음',
  },
  {
    id: 22,
    uuid: '550e8400-e29b-41d4-a716-446655440022',
    applicant: {
      nickname: 'data_yoona',
      gender: 'FEMALE',
      profile_img_url: 'https://cdn.example.com/profiles/yoona.png',
    },
    available_time: '평일 오후',
    has_study_experience: true,
    status: 'ACCEPTED',
    applied_at: '2025-10-23 13:45',
    self_introduction: '데이터 시각화에 흥미가 있습니다.',
    motivation: '데이터를 시각적으로 표현해보고 싶어요.',
    objective: 'D3.js 및 chart 라이브러리 활용.',
    study_experience: '데이터 기반 대시보드 개발 경험 있음',
  },
  {
    id: 23,
    uuid: '550e8400-e29b-41d4-a716-446655440023',
    applicant: {
      nickname: 'fullstack_sangwoo',
      gender: 'MALE',
      profile_img_url: 'https://cdn.example.com/profiles/sangwoo.png',
    },
    available_time: '주말 오후',
    has_study_experience: true,
    status: 'REJECTED',
    applied_at: '2025-10-13 20:14',
    self_introduction: '프론트와 백 모두 좋아하는 풀스택 지망생입니다.',
    motivation: '협업 환경에서 풀스택 역량을 키우고 싶습니다.',
    objective: 'API와 UI 통합 실습.',
    study_experience: 'MERN 프로젝트 진행 경험 있음',
  },
]
