import type { ApplicantDetail } from '@/interfaces/_applicantDetailInterface.js'

export const dummyApplicantDetails: ApplicantDetail[] = [
  {
    id: 1,
    uuid: 'a1b2c3d4-e29b-41d4-a716-446655440001',
    applicant: {
      nickname: 'django_kim',
      profile_img_url: 'https://cdn.example.com/profiles/django_kim.jpg',
      gender: 'MALE',
    },
    self_introduction:
      '안녕하세요. Django 백엔드 개발자를 목표로 공부하고 있습니다.',
    motivation: '실무 프로젝트 경험을 쌓고 싶어서 지원하게 되었습니다.',
    objective: '3개월 내에 Django REST Framework를 활용한 API 개발 능력 향상',
    available_time: '평일 저녁 19:00~21:00, 주말 오전 10:00~12:00',
    has_study_experience: true,
    study_experience: 'React 스터디를 통해 팀 프로젝트를 완성했습니다.',
    status: 'PENDING',
    applied_at: '2025-01-15 14:30',
  },
  {
    id: 2,
    uuid: 'b2c3d4e5-e29b-41d4-a716-446655440002',
    applicant: {
      nickname: 'frontend_lee',
      profile_img_url: 'https://cdn.example.com/profiles/frontend_lee.jpg',
      gender: 'FEMALE',
    },
    self_introduction:
      'React와 TypeScript를 공부하며 프론트엔드 개발에 집중하고 있습니다.',
    motivation: '팀 협업을 통해 실무 감각을 익히고 싶습니다.',
    objective: '디자인 시스템을 적용한 UI 컴포넌트를 제작하는 것이 목표입니다.',
    available_time: '주중 오후 8시~10시',
    has_study_experience: true,
    study_experience: '2개월간 사이드 프로젝트를 진행했습니다.',
    status: 'ACCEPTED',
    applied_at: '2025-02-10 11:22',
  },
  {
    id: 3,
    uuid: 'c3d4e5f6-e29b-41d4-a716-446655440003',
    applicant: {
      nickname: 'node_han',
      profile_img_url: 'https://cdn.example.com/profiles/node_han.jpg',
      gender: 'MALE',
    },
    self_introduction:
      'Node.js를 중심으로 서버 개발을 공부하고 있는 대학생입니다.',
    motivation: 'API 설계와 배포 경험을 쌓고 싶습니다.',
    objective: 'Express와 PostgreSQL을 이용한 프로젝트 완성',
    available_time: '주말 오후',
    has_study_experience: false,
    study_experience: '',
    status: 'PENDING',
    applied_at: '2025-02-22 18:10',
  },
  {
    id: 4,
    uuid: 'd4e5f6g7-e29b-41d4-a716-446655440004',
    applicant: {
      nickname: 'ai_harin',
      profile_img_url: 'https://cdn.example.com/profiles/ai_harin.jpg',
      gender: 'FEMALE',
    },
    self_introduction:
      'AI 모델을 웹 서비스에 연동하는 것을 목표로 공부 중입니다.',
    motivation: '웹과 머신러닝의 연결 구조를 이해하고 싶습니다.',
    objective: 'TensorFlow.js를 활용한 간단한 이미지 분류 앱 제작',
    available_time: '평일 오후 7시 이후',
    has_study_experience: true,
    study_experience: 'AI 스터디에서 신경망 모델을 구현했습니다.',
    status: 'REJECTED',
    applied_at: '2025-03-01 09:45',
  },
  {
    id: 5,
    uuid: 'e5f6g7h8-e29b-41d4-a716-446655440005',
    applicant: {
      nickname: 'uiux_haeun',
      profile_img_url: 'https://cdn.example.com/profiles/uiux_haeun.png',
      gender: 'FEMALE',
    },
    self_introduction:
      'UI/UX 디자인과 프론트엔드 개발을 함께 공부하고 있습니다.',
    motivation: '사용자 경험을 개선하는 인터페이스를 구현해보고 싶습니다.',
    objective: '피그마 디자인을 React로 구현하는 연습을 하고 싶습니다.',
    available_time: '평일 오전 10시~12시',
    has_study_experience: true,
    study_experience: '디자인 툴 스터디를 통해 피그마 협업 경험이 있습니다.',
    status: 'REJECTED',
    applied_at: '2025-03-08 15:30',
  },
  {
    id: 6,
    uuid: 'f6g7h8i9-e29b-41d4-a716-446655440006',
    applicant: {
      nickname: 'data_sangho',
      profile_img_url: 'https://cdn.example.com/profiles/data_sangho.jpg',
      gender: 'MALE',
    },
    self_introduction: '데이터 분석과 시각화에 관심이 많습니다.',
    motivation: '데이터 기반의 인사이트를 시각적으로 표현해보고 싶습니다.',
    objective: 'D3.js를 활용한 시각화 대시보드 제작',
    available_time: '주말 오전',
    has_study_experience: true,
    study_experience: 'Python 기반 데이터 분석 프로젝트 경험이 있습니다.',
    status: 'ACCEPTED',
    applied_at: '2025-03-10 14:12',
  },
  {
    id: 7,
    uuid: 'g7h8i9j0-e29b-41d4-a716-446655440007',
    applicant: {
      nickname: 'pm_han',
      profile_img_url: 'https://cdn.example.com/profiles/pm_han.jpg',
      gender: 'FEMALE',
    },
    self_introduction: '기획과 개발의 협업 과정을 배우고 있는 PM 지망생입니다.',
    motivation: '프로덕트 기획에서 개발까지의 흐름을 경험하고 싶습니다.',
    objective: '개발자와 함께 일하는 방식에 익숙해지는 것이 목표입니다.',
    available_time: '평일 오후 6시 이후',
    has_study_experience: true,
    study_experience: '해커톤에서 PM 역할을 맡은 경험이 있습니다.',
    status: 'PENDING',
    applied_at: '2025-03-15 20:40',
  },
  {
    id: 8,
    uuid: 'h8i9j0k1-e29b-41d4-a716-446655440008',
    applicant: {
      nickname: 'cloud_yun',
      profile_img_url: 'https://cdn.example.com/profiles/cloud_yun.jpg',
      gender: 'MALE',
    },
    self_introduction:
      'AWS와 Docker를 활용한 배포 자동화에 관심이 많은 개발자 지망생입니다.',
    motivation: '실제 배포 파이프라인을 직접 구성해보고 싶습니다.',
    objective: 'CI/CD 구축과 AWS EC2 배포 자동화 구현',
    available_time: '토요일 오전',
    has_study_experience: true,
    study_experience: 'Docker 기반 서버 환경 구축 경험이 있습니다.',
    status: 'REJECTED',
    applied_at: '2025-03-22 13:25',
  },
  {
    id: 9,
    uuid: 'i9j0k1l2-e29b-41d4-a716-446655440009',
    applicant: {
      nickname: 'react_sujin',
      profile_img_url: 'https://cdn.example.com/profiles/react_sujin.png',
      gender: 'FEMALE',
    },
    self_introduction:
      'React로 웹 서비스를 개발하고 있는 프론트엔드 개발자 지망생입니다.',
    motivation: '컴포넌트 설계 능력을 높이기 위해 지원했습니다.',
    objective: 'React Hook과 Context API를 활용한 프로젝트 완성',
    available_time: '평일 오후 7시 이후',
    has_study_experience: true,
    study_experience: '토이 프로젝트 중심의 React 스터디 참여 경험이 있습니다.',
    status: 'ACCEPTED',
    applied_at: '2025-03-25 10:11',
  },
  {
    id: 10,
    uuid: 'j0k1l2m3-e29b-41d4-a716-446655440010',
    applicant: {
      nickname: 'python_dongha',
      profile_img_url: 'https://cdn.example.com/profiles/python_dongha.png',
      gender: 'MALE',
    },
    self_introduction: 'Python으로 데이터 분석과 웹 개발을 배우고 있습니다.',
    motivation: '풀스택 개발 환경을 경험하고 싶습니다.',
    objective: 'Flask와 React를 결합한 웹 프로젝트 완성',
    available_time: '주말 오전',
    has_study_experience: true,
    study_experience: 'Flask 기반 팀 프로젝트 경험이 있습니다.',
    status: 'PENDING',
    applied_at: '2025-03-30 09:00',
  },
  {
    id: 11,
    uuid: 'k1l2m3n4-e29b-41d4-a716-446655440011',
    applicant: {
      nickname: 'infra_yujin',
      profile_img_url: 'https://cdn.example.com/profiles/infra_yujin.jpg',
      gender: 'FEMALE',
    },
    self_introduction:
      '인프라 자동화와 DevOps 환경 구축에 관심 있는 주니어 개발자입니다.',
    motivation: 'CI/CD와 Docker Compose 환경을 직접 구성해보고 싶습니다.',
    objective: 'GitHub Actions를 이용한 자동 배포 파이프라인 구축',
    available_time: '주중 오후',
    has_study_experience: true,
    study_experience: 'Docker 기반 배포 경험이 있습니다.',
    status: 'REJECTED',
    applied_at: '2025-04-05 12:15',
  },
  {
    id: 12,
    uuid: 'l2m3n4o5-e29b-41d4-a716-446655440012',
    applicant: {
      nickname: 'seo_dev',
      profile_img_url: 'https://cdn.example.com/profiles/seo_dev.png',
      gender: 'MALE',
    },
    self_introduction:
      'Next.js와 SEO 최적화에 관심이 많은 프론트엔드 개발자입니다.',
    motivation: 'SEO 성능 개선을 실습해보고 싶습니다.',
    objective: 'SSR과 CSR의 차이를 명확히 이해하고 최적화하는 것',
    available_time: '주중 저녁, 주말 오전',
    has_study_experience: true,
    study_experience: 'Next.js 블로그 개발 경험이 있습니다.',
    status: 'REJECTED',
    applied_at: '2025-04-10 18:05',
  },
]
